---
driver:
  name: proxy
  host: localhost
  reset_command: "if(Test-Path $env:ChocolateyInstall) { del $env:ChocolateyInstall -Recurse -Force }"
  port: 5985
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero

platforms:
- name: windows-2012R2

suites:
  - name: chef
    provisioner:
      require_chef_omnibus: 15
    run_list:
      - recipe[gcp_agent::default]